---
- name: Install Kubernetes Dependencies
  hosts: all
  become: true
  vars:
    kubernetes_repo_version: "v1.24"
    centos_version: "7"
  tasks:
    # Clean up any existing Docker CE or Kubernetes repos

    - name: Remove Docker CE repo if it exists
      yum_repository:
        name: docker-ce-stable
        state: absent

    - name: Remove Kubernetes repo if it exists
      yum_repository:
        name: kubernetes
        state: absent

    # Install required packages

    - name: Install required packages
      yum:
        name:
          - jq
          - vim
          - htop
          - curl
          - net-tools
          - yum-utils
          - iptables
          - iproute
        state: present
        update_cache: yes

    # Setup Docker CE repo & install containerd

    - name: Add Docker CE repo
      yum_repository:
        name: docker-ce-stable
        description: Docker CE YUM Repository
        baseurl: https://download.docker.com/linux/centos/{{centos_version}}/x86_64/stable/
        enabled: 1
        gpgcheck: 1
        gpgkey: https://download.docker.com/linux/centos/gpg

    - name: Install Docker CE packages
      yum:
        name:
          - docker-ce
          - docker-ce-cli
          - docker-compose-plugin
          - docker-buildx-plugin
          - containerd.io
        state: present
        update_cache: yes
        exclude: "*kubernetes*"

    # Enable and start Docker service
    - name: Enable and start Docker
      systemd:
        name: docker
        enabled: true
        state: started

    - name: Ensure docker group exists
      group:
        name: docker
        state: present

    - name: Add user to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes
